@extends('template')
@section('titre')
    Accueil
@endsection

@session('main')
<table>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
    <tr>
        <td>element1</td>
        <td>element2</td>
    </tr>
</table>
@endsession
